### PR TITLE
Set Elasticsearch node address in Docker images

### PR DESCRIPTION
**Pull request by lorthirk**
With the release of Datastore REST APIs we need to override Elasticsearch node address and port in APIs and Console Docker images. Also updated documentation, and modified the property override in the ActiveMQ image since we're not using Elasticsearch cluster yet.

I guess the OpenShift's `kapua-template.yml` should be adapted as well.

### CODE REVIEW

**Comment by ctron** [comment]
@lorthirk What is the best way to test of this works?

**Comment by lorthirk** [comment]
@ctron What I did is attach a device running Kapua to the broker, let it send some messages, and then use the Elasticsearch REST APIs to retrieve some data. Unfortunately I have no better solutions...

**Comment by ctron** [comment]
Do you have some `curl` (or something else) statement which I can use to query data?

**Comment by ctron** [comment]
Looks good to me. Although I couldn't really test it up to now.

**Comment by lorthirk** [comment]
To get indexes:
`curl -X GET "http://127.0.0.1:9200/_cat/indices"` 
To get messages:
`curl -X GET "http://127.0.0.1:9200/{INDEX_NAME}/message/_search?size=1000"` 

`{INDEX_NAME}` name must be one returned from the previous call

**Comment by ctron** [comment]
But that queries ES directly, which gets filled by the broker image. So that wouldn't test anything related to these changes?!

**Comment by lorthirk** [comment]
Sorry, you're absolutely right.

What I told you in [my previous comment](https://github.com/eclipse/kapua/pull/409#issuecomment-289463511) was not accurate at all indeed; now that I recall, I tested it using Swagger UI and asking for Data Metrics.

Sorry about that!

**Comment by ctron** [comment]
@hekonsek Any objections merging this?

**Comment by hekonsek** [comment]
@ctron No, everything seems to be OK.

**Pull request merged**
