### PR TITLE
Bump Apache Tomcat version to 8.0.38 - fixing issue #76

### PR DESCRIPTION
**Pull request by kartben**
Signed-off-by: Benjamin Cabé <benjamin@eclipse.org>

### CODE REVIEW

**Comment by muros-ct** [comment]
Please merge into develop.

**Comment by andrejn-ct** [comment]
The issue is back. Version 8.0.38 is no longer available from the mirror. It only serves the version 8.0.39. Changing to https://archive.apache.org/dist/tomcat/tomcat-8/... would solve the problem permanently as they don't seem to remove old releases..

**Comment by kartben** [comment]
+1. That's already how it's done for downloading ActiveMQ anyways...

**Comment by muros-ct** [comment]
+1. I also made my local change to archive. Otherwise it's a moving target.

**Pull request merged**
