### PR TITLE
Replaced target id with client id on jobs target list

### PR DESCRIPTION
**Pull request by muros-ct**
Solution to this problem is solved by separate query on device by its
PK and using client id for more readable display of selected target.
Each target has to be queried, which might cause problems in very long
targets lists.

This solves issue #1326.

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
@muros-ct I have tested this fix and there is one problem. Regardless of how many devices are added - if user clicks on _**Client ID**_ in Job -> Targets, Job Target window freezes (look at the bottom screenshot) and whole browser window has to be refreshed to continue with normal operations. 
I have added 300 devices at once and it took Kapua 2,5 seconds to add all, so I think this lag is not significant (even for 1000+ devices it will be only a few seconds).

screen shot 2018-02-15 at 10 15 48

**Comment by muros-ct** [comment]
@LeoNerdoG This is because there is still sorting enabled on Client Id. Sorting is not possible, because name of client is retrieved by secondary queries. Sort works only on first query that fills data about targets into grid.

@Coduz This might be a problem for all grids that would fetch data this way, by issuing secondary service query.

**Comment by muros-ct** [comment]
Soved issue for now by removing possibility to sort from Client Id and Error Message column.

**Comment by LeoNerdoG** [comment]
I have verified that there is no more freezing. This can be merged when ready.

**Pull request merged**
