### PR TITLE
Roles integration and Authorization refactoring.

### PR DESCRIPTION
**Pull request by Coduz**
Hi all, 

this is the PR for the role integration and authorization refactoring to introduce an entity that collects roles and a permission for a user.

It still miss some javadoc but it can be validated.

Regards, 

_Alberto_

### CODE REVIEW

**Comment by Coduz** [comment]
Hi all, 

I fogot to link the issue.
This PR closes #75 

Regards, 

_Alberto_

**Comment by Coduz** [comment]
Hi all, 

as said in commit message, I've added the javadoc for the API classes.

Regards, 

_Alberto_

**Comment by kartben** [comment]
new files added by this PR are missing copyright/license headers

**Comment by Coduz** [comment]
Rebased onto latest develop.
If build passes, we can merge into develop.

**Pull request merged**
