### PR TITLE
Added available targets to job

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: ana.albic.comtrade <Ana.Albic@comtrade.com>

Brief description of the PR.
All available devices are added to jobs.

**Related Issue**
This PR fixes issue #2285.

**Description of the solution adopted**
If some devices are deleted they are skipped and other available devices are added to job target list.

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2285.

**Comment by LeoNerdoG** [comment]
@ct-anaalbic 
I have retested this and now I can see that Kapua adds the non-existing device anyway and the result is the same as in issue #2221 which has been fixed by you. 

**Screenshot:**
screenshot 2019-01-16 at 14 20 11

Can you please recheck the PR and make the necessarry fixes?

**Comment by LeoNerdoG** [comment]
Hi @ct-anaalbic,
after last commit it looks like that issue has returned - the end result is same as in the original issue. 
Can you please check again? 

**Screenshot:**

**Comment by ct-anaalbic** [comment]
@LeoNerdoG Yes, I can. I will see now.

**Comment by LeoNerdoG** [comment]
@ana I have figured out what is wrong at last. 
If user is trying to add a list of devices and the first device is not in DB any more, Kapua will not throw proper error. 
But if user is trying to add a list of devices and first device is present in DB (it is not deleted) but there is a device somewhere in this list that is not in DB, kapua will successfully add all the other devices and skip the one, which is not in DB. 

So the problem must be in you "if" statement in the fix, please take a look.

**Comment by LeoNerdoG** [comment]
I have verified that this PR with its last commit successfully resolves issue #2285 and can be merged if the solution is OK.

**Pull request merged**
