### PR TITLE
Documents with Kura Kapua connection tutorial

### PR DESCRIPTION
**Pull request by LeoNerdoG**
I have created document which describes Kura - Kapua connection procedure.
This is just first bigger draft as more and more people are asking how to
connect those two. I will enhance it as the time goes. 
If somebody finds mistakes, please correct them. 

This PR is "answer" to Issue #751 . 

Signed-off-by: Leonardo Gaube <leonardo.gaube@comtrade.com>

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
can you (or somebody else) please review and merge this document as it contains info regarding Kura-Kapua connection? I saw the issues regarding this matter and a lot of forum questions so I hope this helps. 

Regards,
Leonardo

**Comment by ctron** [comment]
Thanks for the PR. I only see one issue with this. We already have two locations which describe how to start Kapua using docker. Adding a third location would make it more error prone once we begin changing this.

I would suggest that we consolidate that. One section in the documentation should describe the process, others should only reference it.

What do you think?

**Comment by LeoNerdoG** [comment]
Hi @ctron ,
I am aware of that fact, but I tried to put myself into ordinary user which just tries to link Kura and Kapua. I know, that we are doubling or tripling the same document but I just wanted to make a guide, which contains everything to set up the desired connection. This way I think it is easier for a beginner to link the two. I hope you understand my dilemma. 
But yes, I agree that documentation should be revised and renewed as soon as possible, because competitive projects have much better documentation, guides and tutorials. 

Regards,
Leo

**Comment by riccardomodanese** [comment]
Hi all, I'mo going to merge this pr. I'm aware of the changes requested by @ctron to organize the guide in a better way (avoiding duplication and so on).
So I'm going to open a new issue to track the reorganization of this guide ( #802 ) .

Regards

**Comment by afterski** [comment]
I've tested and it seems to work fine using the default user in kapua.
The information I needed (missing account name) was:
topic.context.account-name: kapua-sys
username: kapua-broker
password: kapua-password

However serializing objects are not allowed in kapua (dec 2017).
http://activemq.apache.org/objectmessage.html

so to get data in the DB
-Dorg.apache.activemq.SERIALIZABLE_PACKAGES=*
needs to be added to
ACTIVEMQ_OPTS in kapua-broker

This is obviously not a production solution but it gets You started with development.

Cheers, Björn

**Pull request merged**
