### PR TITLE
Changed error message if user is deleted

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: ana.albic.comtrade <Ana.Albic@comtrade.com>

Brief description of the PR.
Changed error message if user is deleted.

**Related Issue**
This PR fixes issue #2454

**Description of the solution adopted**
If users with User:read permission is deleted from another browser, error message is changed to be more specific.

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2454.

**Comment by Coduz** [comment]
HI @LeoNerdoG ,

when testing please check also that, with this change, upon login the information of the user existing or not shouldn't not be displayed. 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
I have checked this and the information about user (whether he exists or not) is not displayed at login screen, but there is a different problem: 
If user is deleted from database and the browser is refreshed, then Kapua returns user to login page, which is OK - but the following error is displayed when trying to login again (with kapua-sys or any other user):

Screenshot 2019-03-19 at 09 47 13

@ct-anaalbic can you pelase check this why this is happening? Otherwise the fix is OK.

**Comment by Coduz** [comment]
Any news on this?

**Comment by ct-anaalbic** [comment]
Hi @Coduz 

I have asked you couple of times on Slack about this but there was no answer. Can you please check your slack messages?

Regards,
_Ana_

**Comment by muros-ct** [comment]
@Coduz What do you think by approach in PR #2527.
It doesn't need a new message properties file, it just logs user out and doesn't allow him to log in again, as it doesn't exist.

**Comment by muros-ct** [comment]
I am closing this PR, as it was solved by PR #2527.

**Pull request closed without merging**
