### PR TITLE
Updated Password regex

### LINKED ISSUE #2242: TextFieldValidator for FieldType.PASSWORD regex bug
**Describe the bug**
The current regex used to validate the password when creating a new _Credential_ does not mark as valid this password:

`>}tN9KP(Rn_Vz`

which has the minimum requirements for a password to be valid.

**To Reproduce**
1 . Open the user view 
2. Go to the credential tab
3. Create a new credential of type passowrd with the given password

**Expected behavior**
The password should be marked as valid

**Screenshots**
_None_

**Version of Kapua**
Kapua 1.0.x

**Type of deployment**
[x] Local Vagrant deployment
[x] Docker
[x] Openshift (in its variants) 
[x] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

**Additional context**
Somewhat related to #2241

### PR DESCRIPTION
**Pull request by lorthirk**
Adding a few missing characters in the Password regex, and a regex check in `CredentialServiceImpl` when creating a Password credential.

**Related Issue**
This PR fixes #2242

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
hey @lorthirk,
I have tested this and now Kapua does not accept special symbols at all.
I have tried password with basis "PassW0rd1234", adding special symbols at the end, but none of them works. 
I have tried the following symbols:
!"#$%&'()=?*/+><,;.:-_

Can you please check the regex?

**Comment by lorthirk** [comment]
Uhm... it worked fine on my PC. I did a few tests... but I guess I'll do some more.

**Comment by muros-ct** [comment]
@lorthirk Have you merged my PR with changed tests, that I made to branch on your fork?

**Comment by lorthirk** [comment]
Not yet, since it looks like tests failed on that one. Let me check them and then I'll merge it.

**Pull request merged**
