### PR TITLE
 Snapshot upload error message handling

### LINKED ISSUE #2175: "Upload and apply" Error Message Should Be Handled More Gracefully
If user is trying to upload and apply random file that is not a regular Kura Snapshot file, Kapua returns error message that is not very user-friendly (look at the screenshots).

**Testflow:**
1. Login as kapua-sys  or any other user that has proper pemissions
2. Connect a live Kura device to Kapua (e.g. device0)
3. Go to Devices, select device0 and go to its Configuration -> Snapshots -> Upload and apply
4. Select a file that is not a Kura snapshot and try to upload it. 
**Observe the error message that shows up.**

**Expected behavior**
Kapua should throw a more generic error, e.g. "The file provided is not a valid Kura Snapshot. Please review the file and try again" or something similar. 

**Screenshot No. 1:**
screenshot 2018-11-12 at 14 49 01

**Screenshot No. 2:**
screenshot 2018-11-12 at 14 48 09

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

### PR DESCRIPTION
**Pull request by ct-ajovanovic**
Brief description of the PR.
 Snapshot upload error message handling.

**Related Issue**
This PR fixes/closes #2175 

**Description of the solution adopted**
Handled exception thrown when the file chosen for upload is not a valid Snapshot.
Added a new regex for fileUploadField.

**Screenshots**
_None_

**Any side note on the changes made**
_None_

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2175.

**Comment by Coduz** [comment]
Hi @ct-ajovanovic ,

I think that we can also force the `FileUploadField.setAccept()` to `application/xml`. 
It should set the `accept` attribute of the tag `input` of type `file`.
Does it makes sense?

Regards, 

_Alberto_

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
I tried adding `setAccept()` property you suggested like this
`fileUploadField.setAccept("application/xml");`
I agree, filtering the displayed results and showing only _xml_ files in the opened dialog could be useful.
But, for me this worked only in Chrome and not in Mozilla or IE. The other two browsers displayed all files. User also has the option of changing result type from xml to all files, and chose the wrong file type.
The validation wouldn't work well without the regex.
Should this be added as well? Besides the regex? 

Thanks
_Aleksandra_

**Comment by Coduz** [comment]
Hi @ct-ajovanovic ,

it seems strange that it does not work with all browsers, since [W3Schools accept documentation](https://www.w3schools.com/tags/att_input_accept.asp) reports that support for that property is supported. 

I think could make sense to add it anyway, since it improves the user experience, even if you saw it working only on Chrome.

Regards, 

_Alberto_

**Comment by ct-ajovanovic** [comment]
@coduz I added the requested property for fileUploadField. I hope everything is ok now.
@LeoNerdoG Can you please recheck this?

**Comment by Coduz** [comment]
Please rebase on the latest `develop`

**Comment by LeoNerdoG** [comment]
Hi @ct-ajovanovic @Coduz,
I have tested this and realized that limit of 255 characters would be better than 64 characters that we have no. @ct-ajovanovic can you please increase the limit from 64 to 255? 
Otherwise I see no problems, so I think this can be merged.

**Comment by ct-ajovanovic** [comment]
Hi @Coduz 
I rebased the branch and updated the character limit as @LeoNerdoG  suggested. 
Can you please check if everything is ok now?
Thanks
_Aleksandra_

**Comment by Coduz** [comment]
All good! :D

**Pull request merged**
