### PR TITLE
fixes #870, #871, #895, #902

### LINKED ISSUE #870: Pages in Groups do not work
When creating Groups, if total number exceeds one page, we cannot go to next page (next page, last page, previous page and first page buttons are not working). 

TestFlow: 
1) Log in as kapua-sys
2) Go to Groups, create 100+ groups
3) Try to switch to page 2, last page, back or first page. 
**When trying to change pages, GUI flashes, but Kapua does nothing.** 

screen shot 2017-10-16 at 13 23 16

Browsers used:
- Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit))
- Safari (Version 11.0 (12604.1.38.1.7))
- Mozilla Firefox (56.0.1 (64-bit))
- Opera (Version 48.0.2685.39)

### PR DESCRIPTION
**Pull request by bojanutkovic**
Signed-off-by: Bojan Utkovic <bojan.utkovic@comtrade.com>

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hi @bojanutkovic , I have merged develop and this commit and this combination resolves issue #870 , I think it resolves all the others also, but I will check. 
After that, we can merge into develop.

**Comment by LeoNerdoG** [comment]
@bojanutkovic @lorthirk 
I am confirming that this PR indeed resolves Issues #870 , #871 , #895 and #902 .

**Comment by bojanutkovic** [comment]
Please check also #937 and #929.

**Comment by lorthirk** [comment]
This PR should also fix #921, #929 and #937

**Comment by LeoNerdoG** [comment]
@bojanutkovic @lorthirk ,
I am verifying that issues #937 , #929 , #955 , #957 , #937 and #921  are solved with this PR.

**Pull request merged**
