### PR TITLE
Changed error message if account name is changed in Kura

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: ana.albic.comtrade <Ana.Albic@comtrade.com>

Brief description of the PR.
Changed error message in device grids if parameter in Kura is changed.

**Related Issue**
This PR fixes issue #2193 

**Description of the solution adopted**
If account name is changed on Kura side from _kapua-sys_ to some other, then error message is changed on right bottom corner.

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2193. 
Can one of te committers please check if the solution is OK and merge?

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
can you elaborate what you thought with the upper comment? 
As I see it, there are two ways to explain yout comment:

1. When device does not have "account-name" parameter configured as it should be and kapua starts throwing the error described above for every tab in devices (assets, command, packages, bundles, configuration); I think this is Ok, because this is the core problem of the issue.

2. if you meant that this error message is thrown everywhere if suddenly the "account-name" parameter is wrong - I have test this and I get this error only when there is actually a problem with "account-name" paramter. 

Did I understood you correctly?

**Comment by Coduz** [comment]
Hi @LeoNerdoG 

I meant the 2nd one. 
If you have any error during the request response, the error shows as "Account-name wrong". 

If we run any device management operation that takes longer than the default timeout (30s) like:

Device command exec
`ping 8.8.8.8 -c 35`

will result in:

 ```
org.eclipse.kapua.service.device.call.kura.exception.KuraMqttDeviceCallException: The "Account-Name" parameter is not properly set on the device. Please check the parameter and reconnect the device.
kapua-console_1  | 	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.send(KuraDeviceCallImpl.java:137)
kapua-console_1  | 	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.execute(KuraDeviceCallImpl.java:73)
kapua-console_1  | 	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.execute(KuraDeviceCallImpl.java:43)
kapua-console_1  | 	at org.eclipse.kapua.service.device.management.commons.call.DeviceCallExecutor.send(DeviceCallExecutor.java:129)
kapua-console_1  | 	at org.eclipse.kapua.service.device.management.command.internal.DeviceCommandManagementServiceImpl.exec(DeviceCommandManagementServiceImpl.java:86)
kapua-console_1  | 	at org.eclipse.kapua.app.console.core.servlet.FileServlet.doPostCommand(FileServlet.java:204)
kapua-console_1  | 	at org.eclipse.kapua.app.console.core.servlet.FileServlet.doPost(FileServlet.java:75)
kapua-console_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
kapua-console_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
kapua-console_1  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
kapua-console_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
kapua-console_1  | 	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
kapua-console_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
kapua-console_1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
kapua-console_1  | 	at org.eclipse.kapua.app.console.core.filter.KapuaWebFilter.executeChain(KapuaWebFilter.java:43)
kapua-console_1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
kapua-console_1  | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
kapua-console_1  | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
kapua-console_1  | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
kapua-console_1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
kapua-console_1  | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
kapua-console_1  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
kapua-console_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
kapua-console_1  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
kapua-console_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
kapua-console_1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
kapua-console_1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
kapua-console_1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
kapua-console_1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:503)
kapua-console_1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
kapua-console_1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
kapua-console_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
kapua-console_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
kapua-console_1  | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
kapua-console_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
kapua-console_1  | 	at java.lang.Thread.run(Thread.java:748)
kapua-console_1  | Caused by: org.eclipse.kapua.service.device.call.kura.exception.KuraMqttDeviceCallException: Error: 
kapua-console_1  | 	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.send(KuraDeviceCallImpl.java:134)
kapua-console_1  | 	... 53 common frames omitted
kapua-console_1  | Caused by: org.eclipse.kapua.transport.mqtt.MqttClientException: Error: org.eclipse.kapua.transport.message.mqtt.MqttTopic@6a8eb9d8
kapua-console_1  | 	at org.eclipse.kapua.transport.mqtt.MqttFacade.sendSync(MqttFacade.java:90)
kapua-console_1  | 	at org.eclipse.kapua.transport.mqtt.MqttFacade.sendSync(MqttFacade.java:32)
kapua-console_1  | 	at org.eclipse.kapua.service.device.call.kura.KuraDeviceCallImpl.send(KuraDeviceCallImpl.java:129)
kapua-console_1  | 	... 53 common frames omitted
```

which is not correct. 

The problem with having the wrong account name is that the device is not able to receive the request, and the request itself goes on timeout. So the only thing that the platform can do is report a timeout. 

What's your opinion on this?

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
hey @Coduz,
I tested this now and I can see what is the problem. I suggest that we modify the error message a bit, to look something similar to: "Timeout exception occurred. Either "Account-Name" parameter is not properly set on the device or the command timed out. Please check the parameters and/pr reconnect the device." sowe have both scenarios covered (timeout and the account-name error). 

What do you think? Is this a good idea?

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

I would only state that the request sent to the device has timeout while waiting the response from the device.

The actual reason why this can happen are a lot

Device disconnected and LWT not yet triggered
The request has been received and accepted but processing took longer than the defined timeout
The request has been received and accepted but processing has caused an internal error
Account name wrong
Connection status out of sync with the DB

I think that would be better to have all of the possible scenarios listed as a Troubleshoot guide on docs. Would be that a good idea? 

Regards,

_Alberto_

**Comment by LeoNerdoG** [comment]
Oh,...Troubleshoot guide - that would be nice and I have a couple of things on my own I think that would fit there. 
But yes, you are right. If there are more than 2,3 scenarios for this, then I suggest that we change this message to "Operation has timed out. Please check the parameters and/or reconnect the device."

Maybe if someone could provide a basis for Troubleshoot guide, I could add my 5 cents. I can make it myself, but currently I don't have time. 

Regards,
Leo

**Comment by Coduz** [comment]
I'm fine with that message. 
I would also remove the added exception code and use the existing one.

**Comment by ct-anaalbic** [comment]
Hi @Coduz , @LeoNerdoG ,

I close this PR because lot of changes are made and code is organized on different way. I will open new PR regarding this issue.

**Comment by ct-anaalbic** [comment]
Hi all,

This issue is resolved and error message is changed. So new PR which refers to issue #2193 won't be created again.

Best regards, 
Ana

**Pull request closed without merging**
