### PR TITLE
Targets deselected on refresh

### PR DESCRIPTION
**Pull request by ct-goranpalibrk**

### CODE REVIEW

**Comment by ct-goranpalibrk** [comment]
Fix for issue #1748

**Comment by Coduz** [comment]
Can you please link the correct issue? 
This is referring the PR itself 😅

**Comment by ct-goranpalibrk** [comment]
@Coduz I changed that mistake, sorry :)

**Comment by ct-goranpalibrk** [comment]
This PR is closed because new PR for this issue is made. New PR is #1758

**Pull request closed without merging**
