### PR TITLE
Added tests for password and email check

### PR DESCRIPTION
**Pull request by LeoNerdoG**
Added test for checking passwords (length, permitted symbols,...) and emails (format, length, symbols...).

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
I added two more sets of tests for ArgumentValidator. They are almost identical as the previous ones. Can you take a look and merge this? 

Best regards,
Leonardo

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

can you please rebase this PR on the latest develop?

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
I have rebased this PR and will push it again in a few minutes (just checking if everything is OK). 

Regards,
Leonardo

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
I will close this PR and make another one, because of some confusion when rebasing...

Regards,
Leonardo

**Pull request closed without merging**
