### PR TITLE
Minor performance issues

### PR DESCRIPTION
**Pull request by AnaScarlet**
Signed-off-by: AnaScarlet <laz1anastasiya@gmail.com>

### CODE REVIEW

**Comment by ctron** [comment]
I will check with EMO if using a GitHub address it possible.

**Comment by ctron** [comment]
I got back a reply from the Eclipse Management Organization (EMO), using GitHubs "noreply" e-mail addresses is not allowed. They will in the future announce some clarification about that.

So it would be great if you could re-sign the PR with your normal e-mail address.

**Comment by AnaScarlet** [comment]
I wanted to hide my normal email address from GitHub though. Is there any
way to do that while signing the PR with my normal address? Is it just the
sign-off-by that needs to have my normal email or do my Git and GitHub
emails need to be the same as that too?

On Jun 3, 2017 8:57 AM, "Jens Reimann" <notifications@github.com> wrote:

I got back a reply from the Eclipse Management Organization (EMO), using
GitHubs "noreply" e-mail addresses is not allowed. They will in the future
announce some clarification about that.

So it would be great if you could re-sign the PR with your normal e-mail
address.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eclipse/kapua/pull/636#issuecomment-305980078>, or mute
the thread

**Comment by ctron** [comment]
So from what I know there are two fields, author and "signed off". Fit contributors both are required to be set and it sounds unreasonable to me to use different ones. As long as GitHub allows you to push those changes I think you are good to go. But your account at Eclipse and the ECA must use your real email address.

**Pull request closed without merging**
