### PR TITLE
Fixed QA test random failure

### LINKED ISSUE #600: Random QA tests failures
Hi all,

after merging #583 some random test failures started to appear more frequently. We had already some random failures on qa tests but they were occasional.

After digging a bit I discovered that is a problem related to how Liquibase script are loaded and the fact that the Kapua Liquibase Client  is run from many different places concurrently. 

The KapuaLiquibaseClient was implemented to copy resources from the jar to a tmp directory and then execute it immediately. With the improvement contained on #583  all scripts gets copied and then executed. 

For the fact that KapuaLiquibaseClient is run from different places it can happen that the copied resources gets overwritten by another KapuaLiquibaseClient is executing them, with even more chance that now that apply of Liquibase scripts takes a bit longer.

I'll fix this making execution of Liquibase script `synchronized` as a simple patch.

Regards,

_Alberto_

### PR DESCRIPTION
**Pull request by Coduz**
Hi all, 

this PR fixes #600 

Regards, 

_Alberto_

### CODE REVIEW

**Comment by ctron** [comment]
What speaks against using Java 8 temp directory creation?

**Comment by ctron** [comment]
Please have a look at PR #610 for a lock free solution to this.

**Comment by Coduz** [comment]
@ctron  please read #586. You cannot have the directory have a variable name. Other test fails otherwise.

**Comment by ctron** [comment]
Ok, I see. That should be put as a comment in the source IMHO.

**Comment by Coduz** [comment]
This is something internal of Liquibase. Is something that we need to change to use the `logicalFilePath` property.

**Pull request merged**
