### PR TITLE
reset filter fields after user input

### PR DESCRIPTION
**Pull request by ct-goranpalibrk**
Signed-off-by: CT\pgoran <goran.palibrk@comtrade.com>

Brief description of the PR.
Filter fields reset when 
**Related Issue**
This PR fixes issue #2489 

**Description of the solution adopted**
Just called reset filter fields method in EntityCRUDToolbar after rendering KapuaDialog.

**Screenshots**
If applicable, add screenshots to help explain your solution

**Any side note on the changes made**
Description of any other change that has been made, which is not directly linked to the issue resolution
[e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2489.

**Comment by LeoNerdoG** [comment]
@Coduz Edit dialog should not be covered anyway since is user is editing something, nothing new is added and therefore the total number of items is not affected.
With the first point I also disagree, but we can change this so filter fields are not affected if user clicks "cancel".

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

when editing a dialog and the result set is filtered, the edit could affect one of the filtered attributes, right? So then it should be removed from the result set, shouldn't it? 

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
@Coduz you are right. 
Should we close this then without merge?

**Comment by Coduz** [comment]
If after an edit or add of entity the grid is refreshed with the current filters, I think that is ok, and we can close this

**Comment by muros-ct** [comment]
So as we agreed on today's skype call, we are closing this PR, and leave the things as they were.

**Pull request closed without merging**
