### PR TITLE
Added test scenarios for user role service

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: ana.albic.comtrade <Ana.Albic@comtrade.com>

Brief description of the PR.
This PR introduces first batch of integration tests for Roles that are added to the user.

**Related Issue**
This PR partially fixes issue #126

**Description of added tests**
Added scenarios for Roles that are added to the user which means:

Test 1: Adding existing role to user
Test 2:   Add user permissions to the role
Test 3: Add device permissions to the role
Test 4: Add job permissions to the role
Test 5: Add device and device_event   permissions to the role
Test 6:   Add account permissions to the role
Test 7:   Add datastore permissions to the role
Test 8:   Add domain, access_info and user permissions to the role
Test 9:   Add endpoint_info permissions to the role
Test 10:   Add group permission to the role
Test 11:   Add role permission to the role
Test 12:   Add scheduler permission to the role
Test 13:   Add tag permission to the role
Test 14:   Add user permission to the role
Test 15:   Delete access role from user
Test 16:   Add deleted role again
Test 17:   Delete permissions from role

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
i have reviewed the code and it looks ok for me. As it is stated in the PR description, this is only the first part of User Role permission tests, more will follow. 

is there a need for a CQ because we have more than 1k lines or is there a way we can merge this, because it is only test code?

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

I've restarted the test twice and it has failed. So it seems like that this PR has some problems.

About the CQ, yes it will be required since there are more than 1000 lines changed.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I will take a look at this and check why it fails.

**Comment by LeoNerdoG** [comment]
Hey @coduz,
Ana has repaired the tests so now everything is OK. 
Can you please file CQ to Eclipse so the process starts as soon as possible (so we don't have this PR open for a long time)?

Thank you!

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
we have reduced the number of lines in this PR - can you merge it now please? 😄

**Pull request merged**
