### PR TITLE
Text in Info/Error messages display change

### LINKED ISSUE #2185: Text In Info/Error Messages Not Aligned
There are some problems with text alignment in some of the error/confirmation windows (see the list bellow). The main problem is, that if text is longer then two lines, some of it goes under the icon on the left. 

List of Error/Info Messages that have unaligned text: 
 - Devices -> Bundles -> Stop
 - Devices -> Configuration -> Services (most of them) -> Save
 - Devices -> Snapshots -> Rollback to
 - Deviecs -> Snapshots -> Upload and Apply (also in issue #2175)

**Testflow:**
1. Login as kapua-sys or any other user that has proper permissions
2. Go to Devices and follow the footsteps described above. 

**Expected behavior**
The text should be aligned as first two rows and should not go under icon on the left side. 

**Screenshot No. 1 (How should all the messages look like):**
screenshot 2018-11-15 at 09 45 25

**Screenshot No. 2 (An example of unalligned text):**
screenshot 2018-11-15 at 09 00 12

**Version of Kapua**
1.1.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 69.0.3497.100 (Official Build) (64-bit))
- Safari (Version 12.0 (13604.3.5))
- Mozilla Firefox (63.0 (64-bit))
- Opera (Version 55.0.2994.44)

### PR DESCRIPTION
**Pull request by ct-ajovanovic**
Signed-off-by: ct-ajovanovic <aleksandra.jovanovic@comtrade.com>

Brief description of the PR.
Text in Info/Error messages display change

**Related Issue**
This PR fixes/closes #2185 

**Description of the solution adopted**
Added css properties to `console.css` file, needed for correct text display in the dialogs. 

**Screenshots**
_None_

**Any side note on the changes made**
_None_

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2185.

**Comment by muros-ct** [comment]
@lorthirk Is it ok to add this to console.css?

**Comment by Coduz** [comment]
I think its ok. 
We just need to check if it affects other components

**Comment by LeoNerdoG** [comment]
Hey,
I have checked this again and from end-user standpoint looks OK so we can merge this 😄

**Pull request merged**
