### PR TITLE
#310 include activemq-stomp JAR

### PR DESCRIPTION
**Pull request by jamesfalkner**
For stomp-over-websockets support.

### CODE REVIEW

**Comment by ctron** [comment]
Hi @jamesfalkner ... in order to contribute to this project you will need to sign a CLA (or ECA how they call it now). Most information should be present at [1], if you need any help just ping me directly.

[1] https://eclipse.org/legal/ecafaq.php

**Comment by ctron** [comment]
Cool. Now you need to re-push the PR. Simply add yourself to the copyright header (which you need to do anyway) and re-push the PR in order to re-trigger the IP validation.

**Comment by jamesfalkner** [comment]
OK, will do, thanks!

As far as the copyright header - is there an example in the repo of someone else adding themselves? I don't see any copyrights other than the Eurotech one..

Also, I am a Red Hat employee, not sure if that changes what I would put in there. I was thinking something like [this](https://github.com/eclipse/kapua/blob/c74b7e37ed5cb1601dcb8d47f468038efa7d3cd1/commons/src/main/java/org/eclipse/kapua/commons/jpa/JdbcConnectionUrlResolver.java#L10)?

**Comment by ctron** [comment]
Cool :smile:  I am using `Red Hat Inc`. When you create a new file, then just add `Red Hat Inc and others` in the first line.

**Comment by jamesfalkner** [comment]
ok will close and issue a new one with the proper changes.

**Pull request closed without merging**
