### PR TITLE
Credential Lockout tests

### PR DESCRIPTION
**Pull request by muros-ct**
New set of tests that cover credential lockout and failed login attempts.

Date calculation on tests was fixed on local date.

Signed-off-by: Uros Mesaric Kunst <uros.mesaric-kunst@comtrade.com>

### CODE REVIEW

**Comment by ctron** [comment]
That looks way better in my opinion. Big thanks!

**Comment by muros-ct** [comment]
@lorthirk These are the basic Lockout and Expiration tests.
I can add more, just tell me which part should be covered with more tests.
Multiple combinations of statuses and dates could be tested.
Lockout scenarios in combination with statuses and expirations...

Most cucumber steps are ready, so it is easy to add scenarios.

**Comment by muros-ct** [comment]
BTW, travis reported failure.
This is test regarding failed login in combination with lockoutPolicy.resetAfter which is potentialy issue.
@lorthirk will check

**Comment by lorthirk** [comment]
Ok, I'm on it. 

Thanks!

**Comment by lorthirk** [comment]
@Coduz do you have any idea about other tests we can perform?

**Comment by muros-ct** [comment]
These are just basic tests that check required functionalities for Lockout and Expiration.
I would suggest that we merge my branch to yours and then merge to develop.
Then I would ask a colegue Leonardo to extend set of tests with more lockout/expiration combinations and test border scenarios.

What do you think?

**Pull request merged**
