### PR TITLE
Corrections added to the name of containers

### PR DESCRIPTION
**Pull request by TristanCP**
-jetty for jetty containers, no extension for tomcat containers, like it was meant to be.

### CODE REVIEW

**Comment by ctron** [comment]
That was actually on purpose. The names of the containers should stay stable IMHO.

**Comment by TristanCP** [comment]
It was on purpose to call "-jetty" the Tomcat container ? Tell me what I'm missing then

**Comment by ctron** [comment]
Hehe .. no, your are right ... calling tomcat containers "-jetty" is definitely wrong 😉  Sorry for not reading your patch completely!

So could you please:
* Sign the ECA [1], if you need help, just let me know and I will try to guide you through the process
* Amend the PR to simply remove the `-jetty` suffix on all names, so that all names are consistent without `-jetty`

It would be best to do the ECA stuff first and push then, because then the "ip-validation" check will pass.

[1] https://www.eclipse.org/legal/ecafaq.php

**Comment by TristanCP** [comment]
I think the problem was my email was not public in my github profile ("noreply@github.com" shown).
Now I don't know how to submit my commit again to the ip-validation, do I need to do a fake change ?

**Comment by ctron** [comment]
You need to squash both commits and add the "Signed-off-by:" footer entry. But every commit needs this footer.

**Comment by TristanCP** [comment]
It looks like my "Signed-off-by: " footer is ignored.

Here is my comment with footer : 
-------------------------------------------------
Container names corrected

and vital new line added

Signed-off-by: Tristan <trrteamlog@gmail.com>

**Comment by ctron** [comment]
I just fixed the branch and squashed the commits.

Please have a look if that it ok with you so I can merge this.

**Comment by ctron** [comment]
Ok, I had to merge it to prevent conflicts with other PRs.

**Pull request merged**
