### PR TITLE
Fix permission error when editing self account details

### LINKED ISSUE #2001: Error When Trying To Edit Account's Settings
Kapua returns an error when user tries to edit Account settings (see the testflow bellow). 

**Testflow:**
1. Login as kapua-sys
2. Go to Child Accounts, add an account (e.g. child0)
3. Set InfiniteChildUsers and Accounts to True
4. Add a user to this account (e.g. user0) with ALL:ALL:ALL:NO permission
5. Login as user0 and click on Settings tab on the left menu and after that Edit.
**Kapua will first thrown an error that user does not have proper permissions to edit the account, but new values will be successfully saved.**

**Expected behavior**
Either Edit button should be disabled or Settings tab not visible, as user does not have Forwardable option set to True.

**Screenshot No. 1 (after clicking on Edit button):**
screen shot 2018-09-12 at 13 10 52

**Screenshot No. 2 (after changing the settings and pressing Submit):**
screen shot 2018-09-12 at 13 10 57

**Version of Kapua**
1.0.0-SNAPSHOT

**Type of deployment**
[ ] Local Vagrant deployment
[x] Docker
[ ] Openshift (in its variants) 
[ ] Others

**Main component affected**
[x] Console (in case of console please report info on which browser you encountered the problem)
[ ] REST API
[ ] Message Broker
[ ] - Others

Browsers used: 
- Google Chrome (Version 68.0.3440.106 (Official Build) (64-bit))
- Safari (Version 11.1.2 (13604.3.5))
- Mozilla Firefox (61.0.2 (64-bit))
- Opera (Version 55.0.2994.44)

### PR DESCRIPTION
**Pull request by lorthirk**
When editing self account informations a permission error was thrown. This PR gracefully manages such error.

**Related Issue**
This PR fixes #2001 

**Description of the solution adopted**
If an user has no `account:read` permission in parent account's informations, the name of the parent account is hidden in the Edit dialog

**Screenshots**
schermata 2018-09-27 alle 11 58 46

**Any side note on the changes made**
N/A

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @lorthirk, I have reviewed this and found some (possible) issues - I do not know which permissions should permit the thigns described bellow. 

1. If user has only **_Account:read permission_**, the Edit button is missing (I don't know if this is OK or not - for now we always just disabled buttons if user did not have proper permissions - screenshot No. 1)
2. Although user has only **_account:read:NO_** or _**account:read:NO**_ and _**account:write:NO**_ permissions, the parent account name is visible in the Description list (Screenshot No. 1) but it is not visbible in the Edit dialoge window
3. If user has account:ALL:ALL:YES permissions, parent account name in Edit dialog window is still not visible (basically Parent account parameter in Edit dialogue widnow is not shown at all, regardles of the user's permission)

Screenshot No. 1:
screen shot 2018-09-27 at 13 24 54

Screenshot No. 2:
screen shot 2018-09-27 at 13 25 10

**Comment by lorthirk** [comment]
Ok, I fixed the first two points. The third one is correct, since the user has no permission on its father.

**Comment by LeoNerdoG** [comment]
I have verified that after latest commit everything is OK. It can be merged when ready.

**Comment by LeoNerdoG** [comment]
This PR also fixes issue #2066 because parent account name is now removed completely.

**Pull request merged**
