### PR TITLE
fix empty error mesages in second scenarios in child accounts

### PR DESCRIPTION
**Pull request by ct-goranpalibrk**
Signed-off-by: CT\pgoran <goran.palibrk@comtrade.com>

### CODE REVIEW

**Comment by ct-goranpalibrk** [comment]
PR for second scenarios  in #977, #978, #979, #981, #982, #983, #984

**Comment by LeoNerdoG** [comment]
@ct-goranpalibrk I have verified that this PR sovles issues #977, #978, #979, #981, #982, #983 and #984 .

**Comment by muros-ct** [comment]
@ct-goranpalibrk 
Please review:
- header of ValidationMessages.properties, it has 2011, 2016, 2018
this should be 2011, 2018
- KapuaExceptionHandler has multiple comments // all others => log and throw internal error code
this is probably bac copy/paste, this comment should only be present in final else statement.

I am also not very pleased with big block of comment-out code in KapuaExceptionHandler.
@Coduz can we remove this?

**Comment by ct-goranpalibrk** [comment]
Requested changes for changing header in Validation messages and for deleting commented code are aplied.

**Pull request merged**
