### PR TITLE
Fixing Broken OpenShift template and docker images for restricted user

### PR DESCRIPTION
**Pull request by alezzandro**
Fixing Broken OpenShift template and docker images for restricted user as per issue #1207 

Basically I've fixed the permissions on assembly `pom.xml` files for kapua-console and kapua-broker.
Then I've added the missing `JAVA_OPTS` and `ACTIVEMQ_OPTS` for kapua-console and kapua-broker in the respective DeploymentConfig on `kapua-template.yml`.

I'm available for any clarification.

### CODE REVIEW

**Comment by lorthirk** [comment]
Hi @alezzandro,

Thanks for the PR! It looks like you have not signed [Eclipse ECA](https://www.eclipse.org/legal/ecafaq.php), so we can't currently merge the code. It would be great if you can sign it, so we can proceed.

**Comment by alezzandro** [comment]
Perfect, I just signed the ECA, I'll provide also a fix for kapua-api pom.xml

**Comment by lorthirk** [comment]
Great!

One last thing though, and I'm sorry for not having mentioned that before.

In order to have a successful ip validation, every commit must have the "Signed-off-by" footer in its message. You can achieve this by just using `git commit -s`, that will append automatically append the footer in the message for you. Of course the email must match the one used when signing the ECA.

Could you please amend your commits by adding such footer? Thank you!

**Comment by alezzandro** [comment]
All done! :+1:

**Comment by lorthirk** [comment]
@alezzandro Unfortunately I see new commits but no "Signed-off-by" in the commit message yet... Could you please verify?

**Pull request merged**
