### PR TITLE
Created Liquibase client

### PR DESCRIPTION
**Pull request by hekonsek**
Created Liquibase client which will be used to:
- update SQL schema in unit tests
- update schema when services start

Client scans classpath for occurences of log files.

@dejanb @ctron @stefanomorson What do you think?

### CODE REVIEW

**Comment by Coduz** [comment]
Hi @hekonsek ,

I looked at the code and as far I understood, it refers to the file "_liquibase.sql_" and execute it right? 

Regards, 

_Alberto_

**Comment by ctron** [comment]
Looks pretty simple. :+1:

**Comment by dejanb** [comment]
Looks good

**Comment by hekonsek** [comment]
@Coduz Yes. This is simple classpath scanner which loads scripts into Liquibase client.

Is it OK to merge it and start using in unit tests for a beginning?

**Comment by Coduz** [comment]
Yes that's fine.. I was concerned about the statically linked file "liquibase.sql" but yesterday you said that adapting the existing SQLs will be done in another phase

**Comment by hekonsek** [comment]
Yes. Also keep in mind that this is a test file only. We will provide dedicated "liquibase.sql" file for each service.

**Comment by hekonsek** [comment]
Merged! Many thanks for reviews.

**Pull request merged**
