### PR TITLE
Added tests for ArgumentValidator

### PR DESCRIPTION
**Pull request by LeoNerdoG**
For now there are only two tests, others will be added when this is merged.

Signed-off-by: Leonardo Gaube <leonardo.gaube@comtrade.com>

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
@Coduz can you please check this pull request? 
Thank you, 
Leonardo

**Comment by Coduz** [comment]
HI @LeoNerdoG ,

yes, sure! 
Next time you can use the menu on the right to ask for reviewers :)

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
For now we from comtrade can't ask for reviewers, Uros told me we have an issue open on your side :) as soon that's fixed, we will surely use it :) 
Regards,
Leonardo

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
I accidentally added two more tests in this PR. Can you still merge it into develop? 
I will be more careful in the future. 

regards,
leonardo

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

You can add as many test you want :) 
Just make sure to don't exceed 1000 lines added. 
You still have work to do on this PR?

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
ok. I will make more small  PRs rather than one big one. I think that way it will be easier for you to merge them =)
I am done with this PR, i will make another one when ready, so this one can be merged/closed. 

Regards,
leonardo

**Comment by Coduz** [comment]
Ok so I'll go ahead and recheck this and merge it 👍 

The 1000 lines is for Eclipse rules also. They have a special procedure for PR with more than 1000 lines from non-committers of the project.

Regards, 

_Alberto_

**Comment by LeoNerdoG** [comment]
Hi @Coduz ,
I know you have a lot on your mind, but could you merge this pull request if everything is ok? =) 

Best regards,
Leonardo

**Comment by Coduz** [comment]
Hi @LeoNerdoG ,

We were waiting for the candidate release branch to be created.
Now it has been created and now this can be merged!

Thanks,

_Alberto_

**Pull request merged**
