### PR TITLE
Fix a few things in the API doc

### PR DESCRIPTION
**Pull request by ctron**
The described approach only works if you are working on the local
OpenShift machine. It doesn't work remotely.

This approach uses the OpenShift routing for accessing the services.

Also does the documentation make use of environment variables in order
to make it easier to copy and paste from the documentation to the
command line.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by ctron** [comment]
And I also changed from GitHub Markdown to plain markdown for the code sections.

**Comment by Coduz** [comment]
Hi @ctron ,

The serialization of the AccessToken entity has been fixed in #411 and this is the current format:

```
{
  "type": "accessToken",
  "id": "l5_1yIHD3Ao",
  "scopeId": "AQ",
  "createdOn": "2017-03-27T17:00:37.22+02:00",
  "createdBy": "AQ",
  "modifiedOn": "2017-03-27T17:00:37.22+02:00",
  "modifiedBy": "AQ",
  "optlock": 1,
  "tokenId": "eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy5lY2xpcHNlLm9yZy9rYXB1YSIsImlhdCI6MTQ5MDYyNjgzNywiZXhwIjoxNDkwNjI4NjM3LCJzdWIiOiJBUSIsInNJZCI6IkFRIn0.koYBckEw84Mfe-zgfJ7LOcWSGdMiK0bhYoNNYWJNY8e7qdA4cbFwxpivr64sS6xVXY-M7KvACwCVjmnrImUITSKLL1i76cnZAVb9wIoi1fQy3DcYBFJ-4YNdDqrLtzTUTbroqIN6p9NIszl2coV4Ev-jaFGb_5Bl8hmhSktlHTVZTBw4w5iLG_nQhUm_ShOAeeaUiJ_2dYG0l6xngKzyRKMhoUIPK6msolG0PZSvsTct1pR8CQY-BytiVOE8EP-uSJmvn96PMXuquSrrOV1Mg82EoMgWjWC6wxUdeE0nZi0epHTVKfgmQzeZhlWtcyz5BG9Rr3E3jmh6RlKRTcHGZg",
  "userId": "AQ",
  "expiresOn": "2017-03-27T17:30:37.108+02:00",
  "refreshToken": "4d97e180-4665-4fb5-be32-c8fa88711606",
  "refreshExpiresOn": "2017-03-27T22:00:37.108+02:00"
}
```

Can you please change it in the doc?

Thanks,

_Alberto_

**Comment by hekonsek** [comment]
@ctron The problem with `oc status` is that it returns proper address only if you have router configured and host address associated with it. Which is usually not a case for development environment.

Can we keep both `oc status` and `oc get service` methods and write that the former should be preferred, but the latter can be used if you don't have router configured locally?

**Comment by ctron** [comment]
@hekonsek Like that?

**Comment by hekonsek** [comment]
+1

**Pull request merged**
