### PR TITLE
Fixing tests that are dependent on MockedLocator

### PR DESCRIPTION
**Pull request by muros-ct**
Custom cucumber runner for junit was created. This runner
accepts system properties that provided by annotating junit run class.

Pom files ware cleaned of this dependency to system property and all
the tests that were using MockedLocator ware corrected.

This fixes issue #531

Signed-off-by: Uros Mesaric Kunst <uros.mesaric-kunst@comtrade.com>

### CODE REVIEW

**Comment by ctron** [comment]
I really like the approach! You could use [repeating annotations](https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html) in order to get rid of the array. That way you could simply add additional annotations as needed.

**Comment by muros-ct** [comment]
Sure, I will do that. Arrays can get cluttered and hard to read.

**Comment by muros-ct** [comment]
Annotation was replaced with repeatable annotation.
@ctron please take a look

**Comment by muros-ct** [comment]
Hi @ctron, I discussed with Stefano. He said that is ok if you merge.

**Pull request merged**
