### PR TITLE
show description of selected endpoint in another account

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: ana.albic.comtrade <anaalbic95@outlook.com>

Brief description of the PR.
Add description informations for endpoints in child accounts.

**Related Issue**
This PR fixes issue #2217 

**Description of the solution adopted**
changed id parameter in getEndpointDescription method. 

**Screenshots**
If applicable, add screenshots to help explain your solution

**Any side note on the changes made**
Description of any other change that has been made, which is not directly linked to the issue resolution
[e.g. Code clean up/Sonar issue resolution]

### CODE REVIEW

**Comment by lorthirk** [comment]
Hi @ct-anaalbic,

The Eclipse IP Validation is failing for the email address you signed off the commit with. Did you already sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)?

**Comment by ct-anaalbic** [comment]
Hi @lorthirk No I did not. I will do it now.

**Comment by LeoNerdoG** [comment]
I have verified that this PR successfully resolves issue #2217.  @ct-anaalbic when you fix IP validation problem this can be merged. Congrats on first PR. 😸

**Comment by ct-anaalbic** [comment]
I close this PR because another one will be made with right ip validation.

**Pull request closed without merging**
