### PR TITLE
Update user display name automatically

### PR DESCRIPTION
**Pull request by bojanutkovic**
#1600 
Signed-off-by: Bojan Utkovic <bojan.utkovic@comtrade.com>

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hi @bojanutkovic,
I was unable to test this, as there was an issue in develop branch, "preventing" end-user to change any of the parameters of the kapua user (Kapua reports error: "An illegal null value was provided for the argument user.name"), and becasue you did not rebase to latests develop, the issue persists in this PR.
Can you please reabase to develop and push changes again?

**Comment by bojanutkovic** [comment]
@LeoNerdoG  
Sorry about that, please try again.

**Comment by LeoNerdoG** [comment]
@bojanutkovic 
I have found an issue with your solution. It looks like Kapua changes the displayed name in top right corner even if you change display name of user, that is not logged in (example: I am logged in as kapua-sys, but I change display name of kapau-broker user. When I click Submit, the diplayed name in the top right corner will change, although it should not, because I am not logged in as kapua-broker). 

Can you please check this? 
Here is a screenshot. The displayed name should be "3" as I was logged in as kapua-sys, but it is "5" (the displayed name I last changed):
screen shot 2018-05-18 at 10 45 33

**Comment by muros-ct** [comment]
@lorthirk can you please check this implementation of events and their handling.
@LeoNerdoG is checking UX.

**Comment by LeoNerdoG** [comment]
After the last commit everything is OK on the GUI side. After @lorthirk confirms that implementation is good, it can be merged.

**Comment by Coduz** [comment]
This PR will be closed.

we don't want to commit to the usage of events in GWT right now. Although this is a good idea, it would be better to have a plan of migration to use GWT events in all views/components.

Regards, 

_Alberto_

**Pull request closed without merging**
